### ISSUE TITLE
Inverted color bug

### ISSUE THREAD

**Issue by mrjoey98** [otya128/OTVDM#1]
I'm running Microsoft Musical Instruments with otvdm and the first thing I noticed was that the colors within the program are inverted. 
![{18D78EA3-23DB-4C14-8188-D93A00DFF9C2} png](https://user-images.githubusercontent.com/49084307/74498797-c8016780-4eaf-11ea-80f4-883cb5051204.jpg)

Sound plays and everything, but these colors are pretty bothersome.
There's also nothing in the console window.
![Annotation 2020-02-13 222515](https://user-images.githubusercontent.com/49084307/74498829-d780b080-4eaf-11ea-89db-bbc8f53a2e11.jpg)

I am running Windows 10 1909 64-bit and I'm using the most recent version of otvdm.

**Comment by wadim-al** [comment]
Same for Powerhouse game.
![otvdm_2020-06-15_19-26-00](https://user-images.githubusercontent.com/29713984/84682345-2e6dc380-af3e-11ea-9bd1-1d9e6cca29e4.png)

**Comment by skid0033** [comment]
what was the solution ? I have a similar issue, but for me the game is Iron Helix, just half of the stuff is inverted.

<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/c07467b0-7f0c-4834-bd90-fd97ff21356a" />

**Comment by skid0033** [comment]
The parts with proper coloring seems to be video parts,
